name: goal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+9
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.2.1
  google_mobile_ads: ^3.0.0
  provider: ^6.1.1
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.20
  intl: ^0.19.0
  html: ^0.15.0
  google_fonts: ^4.0.4
  intl_phone_number_input: ^0.7.0+2  # For international phone input
  animations: ^2.0.7 # For additional animations
  shimmer: ^3.0.0
  iconsax: ^0.0.8
  firebase_messaging: ^15.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.1
  marquee: ^2.2.2
  fading_edge_scrollview: ^3.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  cloud_functions: ^5.3.1
  flutter_fortune_wheel: ^1.2.0
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  mailer: ^6.0.0
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  android_intent_plus: ^4.0.3
  share_plus: ^7.0.0
  syncfusion_flutter_pdfviewer: ^29.1.38
  path_provider: ^2.1.5
  open_file: ^3.5.10
  dio: ^5.8.0+1
  supabase_flutter: ^2.0.0
  file_picker: ^8.1.2
  csv: ^6.0.0
  introduction_screen: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Uncomment and list your custom assets if needed.
  assets:
      - assets/animations/quiz_success.json
  #   - assets/fonts/
